spring.data.mongodb.uri=mongodb+srv://pranathiaerra_db_user:Pranathi14@cluster0.bvizuso.mongodb.net/ai_test_failure_db
server.port=8081
ollama.url=http://localhost:11434
ollama.model=llama3.2
backend.url=http://localhost:8081
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**